### ISSUE TITLE
Harmonize LilyPond \acciaccatura, \appoggiatura, \grace, \slashedGrace

### ISSUE THREAD

**Issue by gilbertohasnofb** [Abjad/abjad#1076]
Abjad currently has three containers to deal with grace notes, `GraceContainer`, `AppoggiaturaContainer`, and `AcciaccaturaContainer`, but LilyPond actually offers a fourth type of grace note, `\slashedGrace`. It is effectively an acciaccatura without the slur. See the second example [in this page](http://lilypond.org/doc/v2.18/Documentation/notation/special-rhythmic-concerns.html) from LilyPond's manual for a comparison of all four types of grace notes.

**Comment by trevorbaca** [comment]
Hi @gilbertohasnofb I think this will make sense to implement as (merely) a flag on Abjad's `AcciaccaturaContainer`, yes? This should be true assuming that the only difference in output will the substitution of `\slashedGrace` for `\acciaccatura`.

**Comment by gilbertohasnofb** [comment]
@trevorbaca That's an option, of course, but given the name of LilyPond's functions, that might be a bit confusing. LilyPond uses `\appoggiatura` and `\acciaccatura` for _slurred_ grace notes, while `\grace` and `\slashedGrace` are the ones without slur. Since Abjad defines distincts container classes for the former three, it might be less confusing to implement the latter as a child container of the `GraceContainer` class as well.

**Comment by trevorbaca** [comment]
@gilbertohasnofb Ok right I agree that as long as we keep `AcciaccaturaContainer`, `AppoggiaturaContainer` in the system then it we should add `SlashedGraceContainer` for reasons of parallelism.

However, taking the opportunity to go back and read Lily's docs about grace notes makes me think that what we should really do in Abjad is collapse `AcciaccaturaContainer`, `AppoggiaturaContainer` (and the not-yet-implemented `SlashedGraceContainer`) back into just `GraceContainer`.

What that will do is leave two grace container classes in Abjad: `GraceContainer` and `AfterGraceContainer`. (Then `GraceContainer` implements a `command` property that defaults to `grace` and can be set to `acciaccatura`, `appoggiatura`, `slashedGrace` ... but which, importantly, can not be set to `afterGrace`.)

I'm pretty confident that this is what we want. The reason why is because LilyPond seems to treat grace / slashed-grace / acciaccatura / appoggiatura as *merely typographic variants of each other*. Ie, LilyPond doesn't seem to model any differences in *timing* between those four classes of ornament. (By contrast, LilyPond definitely *does* model a clear difference in timing [and spacing] for after-grace notes.)

But before I do the work here to change the model in Abjad (ie, compressing to just `GraceContainer` and `AfterGraceContainer`) can I ask your opinion? Do you think it's worth continuing to model grace / slashed-grace / acciaccatura / appoggiatura as (four) separate things?

Scanning the Abjad codebase, there's an important clue: *there's not one instance in Abjad where `AcciaccaturaContainer` and `AppoggiaturaContainer` are being used contrastively*. Rather, 100% of the cases of grace comparison / management in Abjad are between `GraceContainer` and `AfterGraceContainer`. (Which also explains why `AcciaccaturaContainer`, `AppoggiaturaContainer` inherit from `GraceContainer` and also why no further classes inherit from `AfterGraceContainer`.)

Thinking back historically, I think that when I added `AcciaccaturaContainer`, `AppoggiaturaContainer` I was thinking that we would (perhaps in the very distant future) model differences in *grace displacement* (which is very very little-know property you can find implemented on `abjad.Offset`). I think what I might have felt we would capture in the Abjad object model is my understanding of acciaccature and grace notes being played *before the beat* and contrasting with appoggiature being played *on the beat*.

But as things have evolved we have, in fact, never modeled this difference, not even a little bit. Which makes me think we can probably get away with never bothering to model that particular difference.

So what're your thoughts here? Can we get away with a simplification to `GraceContainer`, `AfterGraceContainer`? Or is there a convincing reason to replicate LilyPond quatrchotomy (+ 1) structure at the level of our classes?

**Comment by gilbertohasnofb** [comment]
@trevorbaca It is really kind of you to be asking for my 2 cents here, I really appreciate it. 

I think the most elegant solution would indeed be to reduce all those grace-note-related classes into just two, `GraceContainer` and `AfterGraceContainer`. That would be not only elegant from the development point of view, but also quite simple from an user point of view.

The only drawback I can see is breaking backward compatibility, but it would probably be worth it in this case. 

Many thanks for taking a look into this.

**Comment by trevorbaca** [comment]
@gilbertohasnofb Very much asking your two cents! And thank you.

Over and over again I find how important it is to be able to reflect with another mind for a little bit about modeling decisions. Thanks for the opportunity to dialog. I'll make the changes today in my development branch, and they'll merge in for the 3.1 build.

**Comment by trevorbaca** [comment]
- [ ] add `abjad.Container.command` to accept `\acciaccatura`, `\appoggiatura`, `\grace`, `\slashedGrace`.
- [ ] remove `abjad.AcciaccaturaContainer`, `abjad.AppoggiaturaContainer`

**Comment by trevorbaca** [comment]
@gilbertohasnofb Ok it's done (in my development branch). I think I'm going to send screenshots of the revised part of the API entry to the Abjad mailing list to let folks take a look.

**Comment by gilbertohasnofb** [comment]
@trevorbaca Looks wonderful, Trevor. Thanks once again.
