### ISSUE TITLE
epsfile

### ISSUE THREAD

**Issue by timpauli** [Abjad/abjad#1080]
First of all thx again for creating abjad.

When you try to include an epsfile:

```
note = abjad.Note("c'4")
markup = abjad.Markup(abjad.MarkupCommand('epsfile', '#Y', 1, "foo.eps"))
abjad.attach(markup, note)
abjad.show(note)
```

lilypond runs into a compilation error.
The epsfile-lilypond-command expects as third argument the path to an epsfile with quotationmarks surrounded. I cant get it to work using abjad. When I insert the filename with extra quotationmarks escaping the inner quotationmarks, escape signs end up in the final lilypond file.

What can I do? Thank you a lot.

**Comment by trevorbaca** [comment]
Yes, this is an Abjad problem that shows up in a couple of different places where Abjad classes attempt to parse Scheme arguments to LilyPond functions.

Your input ...
```
note = abjad.Note("c'4")
markup = abjad.Markup(abjad.MarkupCommand('epsfile', '#Y', 1, "foo.eps"))
abjad.attach(markup, note)
```

... produces ...
```
abjad.f(note)
c'4
- \markup {
    \epsfile
        #Y
        #1
        foo.eps
    }
```

... which is bad because because we want `#"foo.eps"` instead of `foo.eps`.

As it happens -- but in a hacky way -- you can fix this by using an `abjad.Scheme` object with the totally-mysterious-and-almost-certainly-unknown-to-everybody `force_quotes` property set to true:

This input ...
```
note = abjad.Note("c'4")
markup_command = abjad.MarkupCommand(
    'epsfile', '#Y', 1,
    abjad.Scheme("foo.eps", force_quotes=True),
)
markup = abjad.Markup(markup_command)
abjad.attach(markup, note)
```
... produces ...

```
abjad.f(note)
c'4
- \markup {
    \epsfile
        #Y
        #1
        #"foo.eps"
    }
```

... which contains the `#"foo.eps"` that we want.

But there is a better way of handling markups in Abjad!

First, note that working with LilyPond markup is difficult enough as it is. Adding the Abjad markup (and Scheme) classes into the mix usually only makes things more difficult, for exactly the reasons this thread shows: it's never exactly certain how the corner cases get parsed and subsequently passed around the system.

On the other hand, using Abjad to attach `abjad.Markup` objects to leaves in your Abjad score is extremely helpful.

So we've got a two-part situation here: the building-up of complex LilyPond markup is really best done BY HAND, while the attaching (and iterating) of markup in Abjad is best done programmatically.

For these reasons, the way I've moved to handling LilyPond markup in my own Abjad scores involves externalizing nearly 100% of my markup to a separate `markups.ily` file for each score together with the use of "literal" markup in Abjad.

Start by noting that the following is 100% valid LilyPond code; in fact it's super-clean because the complex markup expression has been moved to the top level of the LilyPond file. (We'll pretend that the name of the score you're currently working on is Sierra):
```
sierra-foo-eps-markup = \markup
    \epsfile
    #Y
    #1
    #"foo.eps"

\new Staff {
   c'4
   - \sierra-foo-eps-markup
}
```

What's going on here is that we've *named* the markup expression, which greatly cleans up the note-entry portion of the LilyPond file.

We can achieve this exactly when working with Abjad. First, create a `markups.ily` file that contains the following:
```
sierra-foo-eps-markup = \markup {
    \epsfile
        #Y
        #1
        #"foo.eps"
    }
```

Then use `abjad.Markup` in a "literal" way (ie, with no parsing of input arguments) ...
```
note = abjad.Note("c'4")
markup = abjad.Markup(r"\sierra-foo-eps-markup", literal=True)
abjad.attach(markup, note)
```

... which produces ...

```
c'4
- \sierra-foo-eps-markup
```

... which is exactly what we want.

Of course, our `abjad.LilyPondFile` object needs to contain a LilyPond `\include` statement that gives the path to our `markups.ily` file for the LilyPond `\sierra-foo-eps-markup` to be found.

I've been meaning to document this new, externalized way of working with LilyPond markups in Abjad for a long time now. This thread can serve as a beginning.

To solve your immediate problem you can use the `abjad.Scheme` with `force_quotes=True`, as given at the top of this answer. But I suggest externalizing *all* markup for every score you make as a much cleaner and longer-term way of working.

(CCing @GregoryREvans and @josiah-wolf-oberholtzer here because we have open design discussions about this point and how to go forward.)

**Comment by GregoryREvans** [comment]
@trevorbaca I figured this was the same scheme issue. This example caught me by surprise because I haven't looked much into the MarkupCommand class. At first glance it appears only to intentionally model what is given in the example because of their similarity:
```
>>> circle = abjad.MarkupCommand('draw-circle', 2.5, 0.1, False)
>>> square = abjad.MarkupCommand('rounded-box', 'hello?')
>>> line = abjad.MarkupCommand('line', [square, 'wow!'])
>>> rotate = abjad.MarkupCommand('rotate', 60, line)
>>> combine = abjad.MarkupCommand('combine', rotate, circle)
```
so it seems that working with `eps` is a bit of a hack to begin with (although a smart hack). I think using `#Y` is not ideal for the current style of scheme parsing, but could be the direction we want going forward depending on our various opinions.

I have voiced some of my opinions on this to you directly so I'll mention some things here for posterity. In the past I mentioned something along these lines regarding boolean values. I think it would be okay to expect `#t` when passed into Abjad to transform into `##t` because I feel that the typical Abjad user is Lilypond-savvy enough to be comfortable with certain elements of Scheme syntax. But this logic could also lead us to expect Scheme to always be written raw.

I voiced to you that I'm not sure if I ever want Abjad to parse my Scheme unless it's contained in an imaginary `abjad.Scheme` object or some equivalent. In this scenario, I could include a string such as
```
r"""(tuplet-number::append-note-wrapper(tuplet-number::non-default-tuplet-fraction-text 16 5) "20")"""
```
and expect it when passed through something like `abjad.tweak(tuplet).TupletNumber.text` to transform into the following
```
\tweak TupletNumber.text #(tuplet-number::append-note-wrapper(tuplet-number::non-default-tuplet-fraction-text 16 5) "20")
\times 2/3 {
    c'8
    d'8
    e'8
}
```
*instead* of requiring that I include the preceding octothorpe as is the current situation (quotes are placed around the scheme function if the octothorpe is not included). It's not that I think the current syntax is bad, but at the very least I'm not sure that it is a well-documented behavior.

Since we're interested in documenting complicated markup, in the past I have also used `abjad.LilyPondLiteral('long string of markup information', 'after')` as a way to avoid certain scheme issues or when it is actually more convenient to write raw Lilypond code rather than a series of Abjad commands. While the method of externalizing markups is cleaner and absolutely the *best* option, I think its important to note that in most if not all cases the markup code itself can be written as
```
note = abjad.Note("c'4")
markup = abjad.Markup(r"longer markup code", literal=True)
abjad.attach(markup, note)
```
but this can become frustrating when trying to find an ideal tabspacing for legibility rather than one long string of code.
