### ISSUE TITLE
LilyPondFile.floating()

### ISSUE THREAD

**Issue by nagymusic** [Abjad/abjad#1162]
Just a quick question to ask what happened with `LilyPondFile.floating()` constructor in recent Abjad releases. I know one could use it in Abjad 2.21. I also understand that there're other ways to construct floating time signatures, but I'm just curious as I haven't been able to learn more in the documentation.

Thank you,
~Zvony

**Comment by trevorbaca** [comment]
Hi Zvony (@nagymusic). I removed `abjad.LilyPond.floating()` in favor of `abjad.LilyPond.rhythm()`, which does pretty much the same thing.

Those two constructors are / were there only to help with examples in the Abjad docs (which is why I felt ok collapsing them into a single constructor). For your own scores (or any other real-world work with Abjad), configure your own `abjad.LilyPondFile` objects "by hand" (which I'm sure you've been doing!).
