### ISSUE TITLE
Trilled pitches don't transpose

### ISSUE THREAD

**Issue by GregoryREvans** [Abjad/abjad#1172]
It appears that trill pitches don't transpose with `abjad.Instrument.transpose_from_sounding_pitch()`
mwe:
```python
import abjad


staff = abjad.Staff("c'4 <c' d'>4 c'4 c'4")
for chord in abjad.select(staff).components(abjad.Chord):
    new_leaf = abjad.Note(abjad.inspect(chord).pitches().items[-1], (1, 4))
    abjad.attach(abjad.StartTrillSpan(pitch=abjad.inspect(chord).pitches().items[0]), new_leaf)
    abjad.attach(abjad.StopTrillSpan(), abjad.inspect(chord).leaf(1))
    abjad.mutate(chord).replace(new_leaf)

abjad.attach(abjad.AltoSaxophone(), staff[0])
abjad.Instrument.transpose_from_sounding_pitch(staff)
abjad.f(staff)
```
results in the following:
```
\new Staff
{
    a'4
    \pitchedTrill
    a'4
    \startTrillSpan d'
    a'4
    \stopTrillSpan
    a'4
}
```

**Comment by nivlekp** [comment]
This is still valid with Abjad 3.2.

The updated syntax is:
```python
import abjad


staff = abjad.Staff("c'4 <c' d'>4 c'4 c'4")
for chord in abjad.select(staff).components(abjad.Chord):
    new_leaf = abjad.Note(abjad.get.pitches(chord).items[-1], (1, 4))
    abjad.attach(abjad.StartTrillSpan(pitch=abjad.get.pitches(chord).items[0]), new_leaf)
    abjad.attach(abjad.StopTrillSpan(), abjad.get.leaf(chord, 1))
    abjad.mutate.replace(chord, new_leaf)

abjad.attach(abjad.AltoSaxophone(), staff[0])
abjad.iterpitches.transpose_from_sounding_pitch(staff)

string = abjad.lilypond(staff)
print(string)
```
results in:
```
\new Staff
{
    a'4
    \pitchedTrill
    a'4
    \startTrillSpan d'
    a'4
    \stopTrillSpan
    a'4
}
```

**Comment by nivlekp** [comment]
After briefly looking at the codebase, it should not be too hard to come up with a solution.

I have two solutions in mind:
1. In the `transpose_from_sounding_pitch` method, simply check for the StartTrillSpan indicator and adjust its pitch. This should be a quick solution, but might not be a general one. (Are there any other indicators that we want to check? Is there any other method that would require checking the same indicator(s), e.g., in `transpose_from_written_pitch`?)
2. In the `Iteration` class, we can probably change it so that it can iterate trillspan as well. This might be problematic though (?) since the "note" of the trillspan does not come with a duration.

**Comment by trevorbaca** [comment]
Let's go with solution 1.

As you're guessing, there's room for subtle weirdness with solution 2, basically because all the types of the iteration currently implemented are implementing durated objects (ie, components). The `iterpitches` module that I added in 3.2 might be (is?) a foothold for this not-necessarily-durated iteration. But let's go with solution 1 for now. You wanna try it, @nivlekp?

**Comment by nivlekp** [comment]
Sure, I'll give it a go tomorrow. This is probably quite easy.
