### ISSUE TITLE
Mutation.scale() not scaling durations correctly

### ISSUE THREAD

**Issue by jefftrevino** [Abjad/abjad#1182]
Scaling this two-measure container by a factor of half, i.e.,
```
container = abjad.Container(r"c' ~ c'16 d'8. e'4 f' ~ \times 4/5 {f'16 c'' c'' ~ c'' c'' ~ } c''2.")
abjad.mutate(container).scale(abjad.Multiplier(1,2))
```
yields a result that extends by a sixty-fourth note into a second measure, rather than a result of one-measure duration:
```
{
    c'8
    ~
    c'32
    d'16.
    e'8
    f'4
    ~
    \tweak edge-height #'(0.7 . 0)
    \times 4/5 {
        f'32
        c''32
        c''32
        ~
        c''32
        c''4.
        ~
    }
    c''64
}
```

The result should be this container:
```
correct = abjad.Container(r"c'8 ~ c'32 d'16. e'8 f' ~ \times 4/5 {f'32 c'' c'' ~ c'' c'' ~ } c''4.")
```

I hope to find some time in the coming weekends to investigate what's going on here. From left to right, the first error is that the F4 quarter note remains a quarter note, rather than scaling down to an eighth note.

**Comment by trevorbaca** [comment]
Hi @jefftrevino and thanks for the solid example. I'll take a look at this one and see what I can do.

**Comment by trevorbaca** [comment]
Even more minimal example:
```
container = abjad.Container(r"g'16 a' b' c'' ~ c''2.")
```
<img width="302" alt="container" src="https://user-images.githubusercontent.com/5804733/84938067-b07afb00-b0aa-11ea-9c50-0cc0cb07eb3b.png">

```
abjad.mutate(container).scale(abjad.Multiplier(1, 2))
abjad.f(container)
{
    g'32
    a'32
    b'32
    c''4.
    ~
    c''32
}
```
<img width="312" alt="scaled-container" src="https://user-images.githubusercontent.com/5804733/84938148-c8eb1580-b0aa-11ea-850d-1d03bdc88b95.png">

The bug doesn't have to do with tuplets because the first container has only notes.

The bug almost certainly has to do with ties.

**Comment by trevorbaca** [comment]
Fixed:
```
container = abjad.Container(
    r"c' ~ c'16 d'8. e'4 f' ~ \times 4/5 {f'16 c'' c'' ~ c'' c'' ~ } c''2."
)
```
<img width="534" alt="original" src="https://user-images.githubusercontent.com/5804733/84949909-fee4c580-b0bb-11ea-9976-d5659bce1fa4.png">

```
abjad.mutate(container).scale(abjad.Multiplier(1, 2))
abjad.f(container)
{
    c'8
    ~
    c'32
    d'16.
    e'8
    f'8
    ~
    \times 4/5 {
        f'32
        c''32
        c''32
        ~
        c''32
        c''32
        ~
    }
    c''4.
}
```
<img width="517" alt="scaled" src="https://user-images.githubusercontent.com/5804733/84949937-0ad08780-b0bc-11ea-9a7c-63fec32306d1.png">

The implementation of `abjad.mutate().scale()` was sitting on some really, really old code. Which is great because it gave me a chance to remove almost all of it.

Note that the solution I've added here simplifies the implementation of `abjad.mutate().scale()` enormously. This makes the code maintainable for basically the first time ever. But I've also removed functionality. You used to be able to (try to) scale things by weird multipliers like `5/6` or `7/13` and the like. Now you can only scale things by multipliers that can be mapped to each and every leaf in the music you're working with. So `1/2`, `1/4`, `1/8` (and their inverses) are always ok. So are multipliers like `3/2` and `7/4` that effectively add dots to leaves. (And `2/3` will work to remove dots.) Basically you can try any multiplier and see if it raises an assignability error anywhere or not.

I also removed an ancient `scale_contents` keyword from `abjad.mutate().extract()`.

I'll merge into main so you can try out the new code and see if it works for what you're composing.
