### ISSUE TITLE
Wish: initialize PitchSegment from IntervalSegment

### ISSUE THREAD

**Issue by maribote** [Abjad/abjad#1246]
I’d wish there would be a native way to initialize a PitchSegment from an IntervalSegment. Currently PitchSegments can initialize Notes f. ex. with the make_notes() method, but nothing similar exists for IntervalSegments (unless I'm missing something), so that IntervalSegments are basically a "one way in" only. Being able to directly get a PitchSegment from an IntervalSegment might be useful for making intervallic expansions/compressions, amongst other operations on IntervalSegments, return an output that can be directly applied to the music.

The following example shows an expansion by addition:

```python
import abjad

staff = abjad.Staff("c'8 d'8 e'8 f'8 g'8 a'8 b'8 c''8")
intervals = abjad.IntervalSegment.from_selection(staff)

#For a chromatic expansion we make a list of our intervals expressed in semitones:
L = []
for interval in intervals:
    L.append(interval.semitones)

#We make a new list adding an expansion factor to each of our intervals:
L2 = []
for item in L:
    factor = 1
    item = item + factor
    L2.append(item)
  
segment = abjad.IntervalSegment(L2)
segment
>>>IntervalSegment([3, 3, 2, 3, 3, 3, 2])
```

Our new IntervalSegment can't be used for initializing a PitchSegment. Instead we would have to do:

```python
#We define our starting pitch, f. ex. 0:
L2 = [0]

for item in L:
    L2.append(L2[-1] + item + factor)

segment = abjad.PitchSegment(L2)
segment
>>>PitchSegment([0, 3, 6, 8, 11, 14, 17, 19])
```

—Martín.

**Comment by trevorbaca** [comment]
Hi @maribote! Define a function. And put it in a personal library of compositional technique. Your solution works. (You could go ahead and encapsulate it in a function.) I'll show you a maximally tight one down below.

First, background: the reason `abjad.IntervalSegment` doesn't implement the type of initializer you're looking for is because Abjad's segment classes model order, and only order. Sets are used to model collections that are unordered (and contain no duplicates); segments are used to model collections that are ordered (and may possibly contain duplicates). The distinction is borrowed from Robert Morris.

So when you're initializing your new pitch segment, you're reading the input interval segment as ordered (which is what it is!) and then adding the additional (very nice) idea of **accumulation** at the same time. That idea seems simple enough to you that you're thinking "wow, I wish there were an initializer to already do this thing I'm thinking!" But you can easily imagine that there are many dozens of other structural ideas just like this. And implementing constructors for all of them would immediately bloat Abjad's pitch library. Happily, you can get exactly what you're looking for by just writing a function.

The mathematical idea that models your pitch segment initialization is, precisely, taking a list of cumulative sums.

Abjad's `mathtools` package (in Abjad 3.1, which I think is what you're using) contains `abjad.mathtools.cumulative_sums()` to do this. I've changed the name of the package in Abjad 3.2. So in the examples below I'm writing `abjad.math.cumulative_sums()`. Change the name back for your own tests.

Here's an example:
```
numbers = [3, 3, 2, 3, 3, 3, 2]
abjad.math.cumulative_sums(numbers, start=0)
[0, 3, 6, 8, 11, 14, 17, 19]
```

So you can do this:
```
interval_segment = abjad.IntervalSegment([3, 3, 2, 3, 3, 3, 2])
cumulative_sums = abjad.math.cumulative_sums(interval_segment)
semitones = [_.semitones for _ in cumulative_sums]
abjad.PitchSegment(semitones)
PitchSegment([0, 3, 6, 8, 11, 14, 17, 19])
```

Returning to your example, you can now define a function. Something like this:
```
def accumulate_intervals(intervals, start=0):
    cumulative_sums = abjad.math.cumulative_sums(intervals, start=start)
    return abjad.PitchSegment(cumulative_sums)

staff = abjad.Staff("c'8 d'8 e'8 f'8 g'8 a'8 b'8 c''8")
selection = staff[:]
interval_segment = abjad.IntervalSegment.from_selection(selection)
expanded_intervals = [_.semitones + 1 for _ in interval_segment]
accumulate_intervals(expanded_intervals)
PitchSegment([0, 3, 6, 8, 11, 14, 17, 19])
```

Or even this:
```
def expand_chromatic(selection, start=0):
    interval_segment = abjad.IntervalSegment.from_selection(selection)
    expanded_intervals = [_.semitones + 1 for _ in interval_segment]
    cumulative_sums = abjad.math.cumulative_sums(expanded_intervals, start=start)
    return abjad.PitchSegment(cumulative_sums)

staff = abjad.Staff("c'8 d'8 e'8 f'8 g'8 a'8 b'8 c''8")
expand_chromatic(staff[:])
PitchSegment([0, 3, 6, 8, 11, 14, 17, 19])
```

The moral here is that you don't need Abjad's classes to be changed to give you the input syntax you want. You can have truly any syntax -- and library of pitch transformations -- you want. Just design a function. And then keep it with you in a library of important compositional tools :)

**Comment by maribote** [comment]
Hi Trevor,

thank you for your answer! I guess it was a misunderstanding that I was suggesting to implement an `expand_chromatic()` function in abjad. What I was trying to show is that, while you can easily view the "negative" of the pitches of a PitchSegment (its intervals) by using a PitchSegment directly to initialize an IntervalSegment, once you get to an IntervalSegment, you're stuck there. I didn't know about `cumulative_sums()`, thank you!

Knowing this, I think I can make my feature request more specific: could we add this function to the IntervalSegment class, please? :-)

```python
def accumulate(interval_segment, start=0):
    L = []
    for interval in interval_segment:
        L.append(interval.semitones)   
    cumulative_sums = abjad.math.cumulative_sums(L, start=start)
    return abjad.PitchSegment(cumulative_sums)
```

To toggle between a PitchSegment and an IntervalSegment (pseudo-code):

```python
pitches = abjad.PitchSegment([0, 2, 3, 5, 7])
intervals = abjad.IntervalSegment(pitches)
pitches_ = abjad.IntervalSegment.accumulate(intervals)
pitches_
>>> PitchSegment([0, 2, 3, 5, 7])
```

—Martín.

**Comment by trevorbaca** [comment]
Hi Martín! I'm so confused: why do we need to add anything in Abjad? Can't you just implement / steal the code I showed and keep it in a library for yourself??

**Comment by maribote** [comment]
Hi Trevor,

I guess you’re underestimating the difficulty involved in manually (intuitively) creating a PitchSegment from an IntervalSegment for a regular musician. I just think it might increase the usability of the IntervalSegment, which right now doesn’t have an exit for creative endeavors but seems to be a “read-only” class. But I suppose that your answer means already no ;-).

Of course I can use your code (I supposed!). I can also use what I first posted in the first message which does basically the same. Maybe I over exemplified the problem from the point of view of the user: perhaps it’s what seems so confusing.

Thanks for your kind attention anyways!

www.martinrinconbotero.com

**Comment by trevorbaca** [comment]
Hi Martín,

We'll talk more on Tuesday. All that needs to happen is you need to get comfortable defining functions once you figure out how to do something useful. We're working in a programming language for a reason! ;) Until then, have a good weekend and I'll be looking forward to it!
