### ISSUE TITLE
Clean up storage formats (Abjad, rmakers, nauert)

### ISSUE THREAD

**Issue by nivlekp** [Abjad/abjad#1273]
While I was trying to refactor some of the code in the Nauert extension, I came across a formatting issue similar to this one here: https://github.com/Abjad/abjad-ext-rmakers/blob/db30fc68dc4a3bdc2ef8f991033078b286ddab2a/abjadext/rmakers/makers.py#L8900
In the rmakers example, where `abjad.f(command)` prints `abjadext.stack.Stack(`..., it seems like it would be more informative and consistent if it prints `abjadext.rmakers.Stack(`... instead.

This issue appears if the class is not contained in a module with the same name as the class's. For example, this formatting seems to be okay: https://github.com/Abjad/abjad-ext-nauert/blob/769a995a82a6827ffb6ddd664fb0bf820f410cc3/abjadext/nauert/MeasurewiseQSchema.py#L25
Notice that the class `MeasurewiseQSchema` is contained in the file `MeasurewiseQSchema.py`

Does it seem like a modification is required with the `abjad.f` function?

**Comment by trevorbaca** [comment]
Hi @nivlekp! I'll take a look at it over the weekend, or possibly early next week!

**Comment by nivlekp** [comment]
Sure, @trevorbaca. Take your time please, this is just a minor issue. I am also happy to look into it if you agree that this is a bug.

**Comment by trevorbaca** [comment]
Hi @nivlekp, these are great questions. No "bug" to resolve here, but you're smart to point to the asymmetries here, and we'll be changing them very soon, most likely in 3.3 I'll use the space here to explain, so you can see my thinking on where we're going, and please feel free to evaluate my thinking here, too, so we get an outcome that's nice and consistent for 3.3.

Ok, let's see:

The root of what's going on here is that there are four different "formats" of classes that Abjad uses for different things. The first two formats are just the usual output of `__str__()` and `__repr__()`. These are familiar to Python programmers everywhere, and they don't tend to cause confusion in Abjad. Then there are two other "formats" floating around Abjad's implementation: the "LilyPond format" of an object and / or the "storage format" of an object. The LilyPond format of an object does what you think it should (and so its function is clear). The idea of the "storage format" of an object is something unique I added to Abjad: the storage format is a string that can be passed to Python's `eval()` function and reconstitute an object; as such, the storage format of an object is like a very nicely human-readable version of a pickled object.

A couple of examples make the distinction between LilyPond format and storage format clear.

An Abjad note has a LilyPond format (because notes are of course included in Abjad's LilyPond output):
```
>>> note = abjad.Note("c'4")
>>> abjad.lilypond(note)
"c'4"
```

An Abjad articulation has both a LilyPond format (because included in LilyPond output) and also a storage format, to allow the articulation to be persisted in human-readable format to a text file. You can see the difference between the two formats. The LilyPond format is a string of valid LilyPond input. The storage format is a string of valid Python code that can be passed to `eval()`:
```
>>> articulation = abjad.Articulation("staccato")
>>> abjad.lilypond(articulation)
'- \\staccato'

>>> abjad.storage(articulation)
"abjad.Articulation('staccato')"
```

An Abjad sequence has just a storage format, to allow the sequence to be persisted to file in a human-readable way. )Abjad sequences implement on LilyPond format because Abjad sequences are not written to LilyPond output.) Note, too, that the storage format of an object includes a bunch of line breaks and indents different lines of input in a readable way:
```
>>> sequence = abjad.Sequence([1, 2, 3])
>>> abjad.storage(sequence)
'abjad.Sequence(\n    items=(1, 2, 3),\n    )'
>>> print(_)
abjad.Sequence(
    items=(1, 2, 3),
    )
```

Those three examples demonstrate something of a three-way taxonomy of classes in Abjad: classes that implement only a LilyPond format (like notes, rest, chords); classes that implement only a storage format (sequences, and other data structures used to model compositional thinking, but that do not write out as LilyPond input); and classes that implement both types of format (like articulations).

[To be completely clean here, we have to acknowledge that you can, in fact, currently call `abjad.storage()` on an Abjad note. I have no idea why this is. I suspect it's something that I'll remove quite soon, probably in 3.3.]

Thinking through this trichotomy, the classes in the Nauert repo and the rmakers repo should behave like `abjad.Sequence` in the example above:

1. All the Nauert (and rmaker) classes should implement a storage format; but no class in either package should implement a LilyPond format.

What about `abjad.f()`?

Actually, I've deprecated use of `abjad.f()` in Abjad 3.2! (This is noted in the change log for Abjad 3.2, which I've merged into master but which the users haven't seen yet.) `abjad.f()` remains in the Abjad 3.2 release. And there are still 1477 references to `abjad.f()` in the Abjad API. But part of the work I've given myself in 3.3 is removing `abjad.f()` for good.

Other than the fact that name is cryptic (and an abbreviation, which is otherwise forbidden in Abjad), the motivation for removing `abjad.f()` is precisely to help everyone disambiguate between the different formats of objects floating around in the system: I added `abjad.lilypond()` and `abjad.storage()` new in 3.2 as the first step in fixing this problem.

Likewise, in versions of Abjad prior to 3.2, many classes in the system implemented a `__format__()` method. This was problematic. While `__format__()` is a standard "magic method" in Python, user access to the output of the function is through a string keyword: `format(articulation, "lilypond")` or `format(articulation, "strorage")`, etc. Switching on strings like this is rarely a good idea (and it's a mystery why the Python language developers allowed this in the first place). And we see exactly how this becomes a problem in Abjad: until 3.2 it was never clear from the `__format__()` docstrings which different format(s) any given class would implement. How many different values could that second parameter take? How do you know? The whole situation was an invitation for code rot / drift. And that's exactly what we saw over the course of years.

The new regime of `abjad.lilypond()` / `abjad.storage()` makes the situation completely explicit: newcomers to the system don't even need to learn the distinction between the concepts.

And now, after all this, you can see the motivation for removing `abjad.f()`: `abjad.f()` switches prints either the LilyPond format or the storage format of an object. But neither users nor class designers were ever clear as to which format was being printed.

So what does this mean for the classes in the Nauert repo? I think it means that you want all those classes to have a storage format. And either of two ways of showing the dot-chaining in that output would make sense:

1. "abjadext.nauert.AttackPointOptimizer(...)"
2. "nauert.AttackPointOptimizer(...)"

How to pick between these two?

Well, the answer depends on how we anticipate users to import the package. If users "import abjadext" then option 1 will `eval()` correctly. On the other hand, if users "from abjadext import nauert" then option 2 will `eval()` correctly.

And here I have to acknowledge that users do seem to "import abjadext" more than they "from abjadext import nauert", although I don't understand why this is! In my own composing with the rmakers I always "from abjadext import rmakers". Hence when I get around to cleaning up the rmakers' storage formats (in 3.3) I'm going to use option 2, above.

So I'm not sure yet. Do you have preference(s) between options 1 and 2, above, for the Nauert classes?

**Comment by nivlekp** [comment]
Thanks, @trevorbaca for such a detailed explanation!

I will try to change all the `abjad.f()` in the Nauert extension to either `abjad.lilypond()` or `abjad.storage()` then.

As for the two ways of showing the dot-chaining, I don't have a particular preference.
I use `from abjadext import nauert` rather than `import abjadext` just because the latter results in an import error for some reason and the former seems more accurate. I seldom use `eval()` though so I cannot really foresee either representation would trouble me. However, if you are going to use option 2 for rmakers, I would definitely prefer option 2 as well for Nauert for consistency.

**Comment by trevorbaca** [comment]
Hi @nivlekp, ok great. Yep, I think the right way to go is to change every occurrence of `abjad.f()` in the Nauert classes to `string = abjad.storage()` followed by `print(string)`. That's what I'll be doing in Abjad main, and in the rmakers. (Note that none of the Nauert classes will implement LilyPond format; just storage format.) Copy examples of in Abjad main of objects that implement storage format.

For the dot-chaining that appears in the Nauert classes' storage format, let's make them all of the form `nauert.AttackPointOptimizer`, `nauert.Quantizer` etc. This will parallel what I'll do in the rmakers. (Though note that -- as you pointed out -- the rmaker classes don't do this yet!) This two-part dot-chaining will also meet the two most important criteria for storage format: that the usage parallels what users type, and that the resultant string be evaluable.

I'll leave this issue open as a target for both of us to work towards during 3.3 development: I'll harmonize storage formats in Abjad main and rmakers, you tackle the Nauert classes. We'll release both in 3.3.

**Comment by trevorbaca** [comment]
Done in Abjad 3.3.
