### ISSUE TITLE
Is from_pitch_and_duration redundant?

### ISSUE THREAD

**Issue by maribote** [Abjad/abjad#1330]
Hello,

I've been always creating notes with from_pitch_and_duration, when I have both parameters separated. I think in abjad 3.1 it wasn't possible to write abjad.Note("C#5", (1, 4)), but I see that it is now possible in 3.2. This makes from_pitch_and_duration in principle unnecessary. Does from_pitch_and_duration have another use or will it be eventually removed? I find it frankly practical not having to use from_pitch_and_duration at all in this case.

Regards,
Martín.

**Comment by trevorbaca** [comment]
Hi Martín, for many years (since Abjad 2+) it's been possible to initialize a note with something like `abjad.Note(pitch, duration)`. There are even more ways you can initialize `abjad.Note`, too. Read through `abjad.Note.__init__()` ...

https://github.com/Abjad/abjad/blob/172f3fc48850ef54648dcfc395e7ab066c9a0c0c/abjad/score.py#L4384

... and what you'll find is that the code is a mess, but also that the class supports quite a few initialization patterns.

Long term (on the order of years) I'll probably do precisely the opposite of what you want: the implicit patterns currently available in `abjad.Note.__init__()` will probably all migrate out to become methods with explicit names, like `abjad.Note.from_pitch_and_duration()`. At which point you won't be able to type `abjad.Note("C#5", (1, 4))` any more. But that's years away.

"But `abjad.Note("C#5", (1, 4))` is so much more compact than `abjad.Note.from_pitch_and_duration()`!" Yes, I know. 

The challenge concerns documentation: most of those different patterns for initialization aren't documented anywhere for users to see. (Which is, for example, why you're just now discovering `abjad.Note(pitch, duration)`.) The reason for this is that Sphinx (the Python documentation system we use to automatically document every function in Abjad) knows absolutely nothing about the dozen or so patterns in `abjad.Note.__init__()`, including `abjad.Note(pitch, duration)`. On the other hand, Sphinx knows exactly how to find and document `abjad.Note.from_pitch_and_duration()`. The result is that users discover (and use) `abjad.Note.from_pitch_and_duration()` all on their own, just like you did.

Similar reason that Python's built-in dictionaries have a `dict.fromkeys()` method.

**Comment by maribote** [comment]
Hi Trevor,

ah, I see. Good to know. I’ll stick to the explicit form then. I just found it curious that two apparently different ways of initializing a note yield the same result and was wondering what the future of that situation was so that I don’t have to change my code/manners in the future. There’s not a single line of code in my library/compositions that use the implicit form, so that’s good news for me in the long term, I guess ;-).

www.martinrinconbotero.com
