### ISSUE TITLE
Sphinx code-coloring plugin errors on double braces

### ISSUE THREAD

**Issue by jgarte** [Abjad/abjad#1342]
@trevorbaca @GregoryREvans 

Is this an issue for anybody else?

https://abjad.github.io/examples/magic-square-from-twelve-tone-row.html

The second code snippet's formatting button (i.e. >>>) is not working.

I tried on chromium, firefox, and falkon browser and it's reproducible.

I looked at the .rst file for a moment and wasn't able to figure out the issue.

I'm leaving this as a note to myself or anyone else that can point it out eventually.

**Comment by trevorbaca** [comment]
Hi @jgarte yes I saw it at the time I was authoring the example. It comes from some unknown component in the doc-building toolchain. (Maybe Sphinx, maybe whatever Sphinx plugin we're using to generate those view-code tags.) Codeblocks that contain an overly fancy string confuse whatever part of the doc-building system that is, with exactly the result that you're seeing, ie, deactivated triple chevron. Looking at the example again now, I'd bet it's the line `string = rf"\markup \larger {{ IT \hspace #-0.75 \sub {number} }}"`. Easy to test by temporarily removing that string and rebuilding the docs.

The fix is to restructure the example to somehow remove strings of that type. I didn't bother when I was  authoring the example because it's pretty easy to work around. If you're able to build the docs and come up with a solution, I'll be happy to patch. Otherwise it'll wait until I have time to groom the docs again.

**Comment by jgarte** [comment]
Hi @trevorbaca 

Thanks for sharing your insight. 

Give me a few more days and I'll find the time to try this. 

I am able to build the docs and serve them locally for testing.

**Comment by trevorbaca** [comment]
Confirmed that the Sphinx plugin can't handle double braces, like `{{` and `}}`.

Changed this ...

<img width="594" alt="double-braces" src="https://user-images.githubusercontent.com/5804733/116796146-3a0b9f80-aaa8-11eb-9f32-dcce2ba78e38.png">

... to this ...

<img width="571" alt="no-double-braces" src="https://user-images.githubusercontent.com/5804733/116796148-45f76180-aaa8-11eb-95b1-7f30ecc860ee.png">

... fixing the code coloring:

<img width="747" alt="fixed" src="https://user-images.githubusercontent.com/5804733/116796150-50b1f680-aaa8-11eb-93e0-9931763c872b.png">

**Comment by jgarte** [comment]
@trevorbaca Thanks for fixing that and sharing the above. It is much appreciated! 

Sorry I've been busy the last few weeks to try this.

Maybe sphinx upstream will support double braces in the future...
