### ISSUE TITLE
Model Lilypond's lyrics interface

### ISSUE THREAD

**Issue by jefftrevino** [Abjad/abjad#446]
Starting some choir writing now and can take a stab at an object model of Lilypond's lyrics interface. I hope you'll drop me a line with (1) any conventions of the git commit process I'll need to obey; (2) instructions about where it should live in the hierarchy of things; and (3) what parent classes should be. Reminder of tasks to be modeled: http://www.lilypond.org/doc/v2.19/Documentation/notation/techniques-specific-to-lyrics

**Comment by filmor** [comment]
Any hint on how one could tackle this?

**Comment by josiah-wolf-oberholtzer** [comment]
@filmor We still don't have a model of LilyPond's lyrics. The way we typically deal with lyrics-like behavior is to simply use vertically-aligned markup. We do this because it hasn't been obvious how to translate LilyPond's lyrics model into a fully-formed Abjad lyrics, given the way LilyPond lyrics are tie- and slur-aware, plus considerations for hyphens and continuation lines.

If you wanted to try to tackle this, I would start very simply by modeling LilyPond's `\addlyrics` command as an indicator class. Basically, figure out how to make the following code work:

```
staff = Staff("c'4 d'4 e'4 f'4")
lyrics = indicatortools.AddLyrics('do re mi fa')
attach(lyrics, staff)
```

...resulting in:

```
\new Staff {
    c'4
    d'4
    e'4
    f'4
}
\addlyrics {
    do
    re
    mi
    fa
}
```

**Comment by trevorbaca** [comment]
Still valid in June 2017.

**Comment by trevorbaca** [comment]
I suspect that lyrics handling can now be done with simple combinations of `abjad.Container` and `abjad.LilyPondLiteral`.

If somebody wants to add a few minimal examples of output that we'd like to see here, I can take a stab at showing how to use the core Abjad classes to achieve the effect.

I'll leave this ticket open for another month or two, and then close afterwards.

**Comment by trevorbaca** [comment]
Reopen when active again.
