### ISSUE TITLE
Kill implicit container slip

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#454]
```
staff = Staff("c'4 d'4 e'4 f'4")
container = Container(staff[1:-1])
```

`container` should _not_ be slipped into `staff`.

This is too implicit.

**Comment by trevorbaca** [comment]
+1

**Comment by trevorbaca** [comment]
Still valid in June 2014:
```
staff = Staff("c'4 d'4 e'4 f'4")
container = Container(staff[1:-1])
f(staff)
```
Output:
```
\new Staff {
    c'4
    {
        d'4
        e'4
    }
    f'4
}
```
What interface do we want for this?

I've definitely come to feel that the implicit interfaces offered by container initializers (as in this example) and also container__setitem__() should just be removed: no keywords are possible and the patterns are basically anti-literate because no explicit verbs (like "insert", "replace", "nest" or whatever) appear in code called in these ways.

So if we want to preserve the functionality shown in the example, we should probably come up with an explicit (named) method for it.

**Comment by trevorbaca** [comment]
See #463 too.

**Comment by trevorbaca** [comment]
Two (alternative) paths forward:

1. Preserve the functionality shown (ie, containerize in-staff notes) with a newly created (and explicit) interface.

2. Remove the functionality.

The second of these seems radical. But is it? It's possible that the functionality shown here (containerizing in-staff notes) isn't really being used.

**Comment by trevorbaca** [comment]
Testing shows that restricting the object model to forbid containerizing already-contained music could plausibly work. There's now a commented-out restriction in `Container` that can be activated and run against the codebase. Doing so shows this:

25 doctest failures:
```
    15185 passed, 25 failed out of 15210 tests in 821 modules.
```
74 pytest failures:
```
    74 failed, 10048 passed, 523 skipped in 225.46 seconds
```
This means that very few parts of the codebase rely on containerizing contained music.

**Comment by trevorbaca** [comment]
Further testing shows that the containerize-already-contained-music functionality needs to stay in the system.

The most important case is tupletizing in-staff notes:
```
>>> staff = Staff("c'4 d' e' f' g' a'")                                             
>>> Tuplet((2, 3), staff[:3])                                                       
>>> Tuplet((2, 3), staff[-3:])          
>>> f(staff)
\new Staff {
    \times 2/3 {
        c'4
        d'4
        e'4
    }
    \times 2/3 {
        f'4
        g'4
        a'4
    }
}
```
The functionality turns out to be more than a nice-to-have convenience because this is the way mutate methods like `mutate().scale()` work when duration-scaling certain types of notes and rests.

So we'll go with path number 1 given above and preserve the functionality.

But with fully explicit interface. Example:
```
mutate(staff[:3]).containerize(Tuplet)
```

**Comment by trevorbaca** [comment]
Done in 2.21. Use `mutate().wrap(container)` instead.
