### ISSUE TITLE
Equip rhythm-makers with statal input dictionary; remove rotation=None keyword

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#460]
The pattern is currently implemented as a type of proof-of-concept on EvenDivisionRhythmMaker.

Can be implemented identically on division-makers and the other rhythm-makers.

Do after 2.16.

**Comment by josiah-wolf-oberholtzer** [comment]
Rhythm-makers *having* generators had to be backed out, due to problems with copying, pickling, etc.

However, we could still implement this by allowing an external state memo to be passed into each rhythm-maker at *call* time. That would be particularly clean.

**Comment by trevorbaca** [comment]
Good point. That would work if we feel like we'd use the functionality.

I think I was using the "seeds" input in L'archipel du corps to preserve state during rhythm generation. But thinking back on it I'm pretty sure I could have gotten results that were just as good without state preservation. Remind me again if you're using state preservation?

**Comment by josiah-wolf-oberholtzer** [comment]
I'm definitely using state preservation.

I don't want to make any move on axing rhythm-maker rotation until I have
an external state solution worked out.

Should be doable, and very flexible.

**Comment by jefftrevino** [comment]
I definitely use state preservation.

On Sunday, August 16, 2015, Josiah Wolf Oberholtzer <
notifications@github.com> wrote:

> I'm definitely using state preservation.
>
> I don't want to make any move on axing rhythm-maker rotation until I have
> an external state solution worked out.
>
> Should be doable, and very flexible.
>
> On Sun, Aug 16, 2015, 11:21 Trevor Bača <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Good point. That would work if we feel like we'd use the functionality.
> >
> > I think I was using the "seeds" input in L'archipel du corps to preserve
> > state during rhythm generation. But thinking back on it I'm pretty sure I
> > could have gotten results that were just as good without state
> > preservation. Remind me again if you're using state preservation?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Abjad/abjad/issues/460#issuecomment-131598688>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Abjad/abjad/issues/460#issuecomment-131598852>.
>


-- 
--
Jeff Treviño, Ph.D.
Assistant Professor of Music and Technology
Colorado College

**Comment by josiah-wolf-oberholtzer** [comment]
I think what we need is a "RotationCounter" class. Something subclassing or wrapping a ``collections.Counter`` instance.

We would optionally pass it in to rhythm-makers at call time via the rotation keyword. Like all the rhythm-maker specifiers, a blank one would be created internally if none was specified.

We then teach the rhythm-makers to rotate their sequences by looking up keys in the counter. A talea rhythm-maker' talea counts would look for the key ``talea__counts``. If no key exists, the counter sets that key to zero and returns zero. Therefore no rotation.

We could also give the counter an ``autoincrement`` flag. That would give us a foothold for letting makers cache their exact state, rather than rotating every sequence property by the same value as we currently do. 

If a rotation state object was passed in at call time with ``autoincrement=True``, that object would be incremented in place. Rhythm-makers would continue to only return selections on call. After call, you would know the precise index of rotation of every rotatable sequence used by the maker.


An invasive change, but super flexible and less magic than now.

**Comment by trevorbaca** [comment]
Excellent.

That's a change worth doing the architectural legwork for.

**Comment by trevorbaca** [comment]
Still valid in June 2017.

I wanna get rid of (actually, *generalize*) the `rotation` keyword in the rhythm-makers.

There are many other statal parameters that could be passed into the rhythm-makers.

I have a model working in my own library that passes in (and out) a dictionary of all such statal values. Would need to be integrated into rhythm-makers.

**Comment by trevorbaca** [comment]
Done in the 3.0 externalization of abjad-ext-rmakers.

See the `state` dictionary now attached to the rmakers.
