### ISSUE TITLE
Add IdentityMapped abstract base class.

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#510]
To be used when implementing LilyPondGrob LilyPondGrobInterface and LilyPondContext.

**Comment by josiah-wolf-oberholtzer** [comment]
LilyPondGrob, LilyPondGrobInterface, LilyPondEngraver and LilyPondContext now all implement identity map behavior.

This behavior requires tests.

It remains to be seen if it's worth factoring this behavior out into a base class or metaclass.

**Comment by trevorbaca** [comment]
See ...

https://en.wikipedia.org/wiki/Identity_map_pattern

... for a bare-bones explanation of the identity map pattern.

In general I feel like we've gotten much less use from abstract baseclasses in Python than I ever thought that we would. The community talks about this sometimes, but for years I chose not to listen, not out of obstinance but because ABCs were so useful to me in Java.

I don't really have a strong opinion about the abstracting LilyPondGrob, LilyPondGrobInterface, LilyPondEngraver and LilyPondContext. But I think there's probably a lovely way to abstract the test functionality itself into a dedicated class (without having to subclass the four classes in question).

**Comment by josiah-wolf-oberholtzer** [comment]
True, true. This may not require an ABC, but only a Mixin for the special ``__new__`` functionality.
