### ISSUE TITLE
Refactor expensive formatting properties as methods

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#557]
Proposed changes:
- Replace the property `_format_pieces` with the method `_get_format_pieces()`.
- Replace the property `_lilypond_format` with the method `_get_lilypond_format()`.

Why? For one, methods are more indicative of arbitrary computational cost.

More usefully, we can call `getattr()` and `hasattr()` on the method without executing its body. This leads to fewer confusing bugs such as `hasattr()` returning `False` on a property which raises an error.

**Comment by trevorbaca** [comment]
Yes.

Also see #362 when we get around to this one, too.

**Comment by josiah-wolf-oberholtzer** [comment]
I think this does one better - `hasattr()` shouldn't be called on properties, only methods.

**Comment by trevorbaca** [comment]
+100 to your comment from April: `hasattr()` (and also `getattr()`) should only be called on methods, and not on properties.

We've known this for a while. But it turns out that there are still some places in the codebase where we are (unfortunately) calling `hasattr()` / `getattr()` on properties. Found a really evil one in `StorageFormatAgent` today.

#362 (or something like it) is still the key to fixing all of these: we need to comprehensively remove `hasattr()` / `getattr()` calls from the codebase.

**Comment by trevorbaca** [comment]
Original ticket can now be closed. Both proposals now satisfied:

* Replace the property _format_pieces with the method _get_format_pieces(): done months ago.
* Replace the property _lilypond_format with the method _get_lilypond_format(): done today.

Note that this ticket could be extended almost indefinitely. Why? Because there are probably still a couple dozen properties in the codebase that should be reimplemented as methods.

But this issue will be closed by incoming commit. Note that #362 is still the only comprehensive proposal to fix the underlying pattern.
