### ISSUE TITLE
Replace `abjad.graph()` with `abjad.show(format='graphviz')`

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/abjad#558]
The name `graph` is sitting on expensive lexical real estate. Users are very likely to overwrite Abjad's `graph()` function with a graph of their own.

Both `graph()` and `show()` do effectively the same thing: render an object as a PDF, either via Graphviz or LilyPond.

We can borrow from the behavior of `format()` and pass in an optional `format_specification` keyword, along with any other keyword arguments.

**Comment by trevorbaca** [comment]
Still valid in June 2017:
```
>>> graph
<function graph at 0x101b90a60>
```

**Comment by trevorbaca** [comment]
Question: since we're moving (and recommending our users move) to `abjad`-qualified pathing, does the continued availability of `graph()` become ok?

That is, uses of graph will all be `abjad.graph()`. Which should prevent aliasing with any user-defined function(s) of the same name.

I'm happy to make the change specified at top. But I think universal `abjad.graph()` namespacing may render the problem no longer a problem.

**Comment by josiah-wolf-oberholtzer** [comment]
Let's leave this one open.

I'm really glad that the `abjad` namespacing is making the lexical component of this less of a problem, but I'm still concerned with making `show()` and `play()` parametrizable, i.e. I want classes to be able to vend multiple ways of being shown / played, much like how you can call `format(...)` and receive different input depending on what keywords you pass in.

That could potentially give us this top-level trifecta:
- `format(...)`:
    - generate textual representation of object
    - works with `__format__(...)`
- `show(...)`:
    - generate visual representation of object
    - currently works with `__illustrate__(...)`
    - I want to collapse `__graph__` in 
- `play(...)`:
    - generate audio representation of object
    - currently has no dedicated protocol method
    - currently only generates MIDI output

I'd like those three methods to be able to vend any kind of output that the class knows how to produce, and to generalize the playing/showing code more, reducing the hard coupling to LilyPond in favor of pluggable play/show strategy classes.

Maybe something like...
- `play(Note("c'4"))` calls `Note.__play__(self, format='lilypond')`
- `Note.__play__(self, format='lilypond')` returns a `LilyPondMIDIOutput` object
- `play` calls `LilyPondMIDIOutput.render()` to render it to disk appropriately
- `LilyPondMIDIOutput.render()` returns the file path of the rendered audio
- `play` pops the file path in your default audio player

And then you can plug in `play(Note("c'4"), format='csound')` to generate a hypothetical `CSoundOutput` object, and render that instead of the default MIDI, assuming `Note` knows how to do that.

This is all motivated by my work outside of Abjad, where I'm replacing `show()`, `graph()` and `play()` with slightly different versions, just to use different rendering strategies. If we had a generalized clean architecture, I'd be able to merge some of that code in. And we'd also be reducing our coupling to LilyPond, providing a toe-hold for other output strategies.

**Comment by trevorbaca** [comment]
Definitely in favor of all types of decoupling :)

Hey, how have you found the long-term wear of `format()` to be? I've personally wound up almost loathing it (being humorous here) because even after years of use I have no idea what it's going to give me! ;) And I think that's precisely because of the `format_specification` keyword.

Does that make sense? Like, when you look at the API entry for a class, do you have a solid feeling about the types of format output it's gonna generate? Maybe you do, in which case point me to what I've been missing all these years. I feel like the keyword has meant that the API entry is only as good as our *manual* documentation is for each class: we have to remember to write an explicit example for each value of `format_specification`, which we sometimes forget to do, making code-rot (or at least documentation-rot) an ongoing problem. Sigh.

I suppose the alternative I'm thinking of here is that when he have separate explicit methods (something like hypothetical `__lilypond__()` verus hypothetical `__storage__()` for example) then the documentation system picks up on these and makes it absolutely clear what type of format-output every class is capable of, regardless of whether we write by-hand examples. Which is nifty.

I'm *definitely* down for generalizing hooks for you to integrate into! Extremely so. Also wonder if there's a way of solving the doc-rot problem at the same time?

**Comment by josiah-wolf-oberholtzer** [comment]
Format doesn't bug me that much, but I do feel your pain about the
uncertainty around knowing what the options are, what the default will be,
etc.

I definitely think we can clarify that both in the code and in the docs via
some clear and introspectable naming conventions, probably by applying some
decorators to __format__, teaching it which options are available for the
given class and which is the default.

**Comment by josiah-wolf-oberholtzer** [comment]
And speaking of doc rot, we should discuss type annotations! All of those
"Returns X." sentences at the end of our docstrings can be generated
automatically from code which is also used to verify the correctness of the
code which it documents.
