### ISSUE TITLE
ffmpeg is deprecated but can be replaced with timidity

### ISSUE THREAD

**Issue by chr15m** [Abjad/abjad#607]
The following command will render a midi file directly to .ogg with timidity:

`'timidity %s -Ov -o %s' % (midi_file_path, tmpaudio)`

Is it possible to support this natively?

Thank you so much for this excellent software.

**Comment by chr15m** [comment]
I should note that ffmpeg is no longer available on GNU/Linux as it has been deprecated in favour of avconv.

**Comment by josiah-wolf-oberholtzer** [comment]
@chr15m Good to know. I'll investigate.

**Comment by chr15m** [comment]
Wow! That was quick. I tested this commit and it works well on my system. :+1:

**Comment by josiah-wolf-oberholtzer** [comment]
Thanks. I'll merge this in as soon as I get the Travis-CI tests sorted.

**Comment by josiah-wolf-oberholtzer** [comment]
@chr15m FYI, Travis-CI has whitelisted APT packages for `ffmpeg` and `fluidsynth` but not `timidity`. I was really hoping to finally test the entirety of the IPython extension now that Jupyter allows for running entire notebooks unattended on the command-line. Now we have to skip automated testing of audio output in notebooks. 😣 

But, it works for you, so that's good enough for now.

And thanks for submitting the issue: using `timidity` instead of `fluidsynth` and `ffmpeg` simplifies installation and configuration for our users.
