### ISSUE TITLE
Refactor demos as classes

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/abjad#678]
The implementations of the demos (Bartók, Ferneyhough, Ligeti, Mozart) are ancient.

Each can be refactored into a single class (in a single classfile).

Each could also be refactored as a single segment-maker.

The work will probably only take an afternoon.

The point of the work is pedagogical: as our use of the system has matured, it makes sense to publish our best practices rather than older approaches.

**Comment by josiah-wolf-oberholtzer** [comment]
I wonder about this, though. Does this create additional overhead for the student? It sort of requires that all functionality be present in the class from the start. Introducing functionality piecemeal then becomes more difficult, makes it harder for students to understand the structure and function of the code incrementally. Think about the actual lived experience of a newcomer to Abjad reading through the Ferneyhough example for the first time, written as a series of functions, then as a single class. Pedagogically, I think leaving these examples as a series of gradually introduced functions is actually more fruitful.

**Comment by ajyoon** [comment]
My experience as a learner relatively new to Python was fair deal of confusion trying to sift through the demo files and figure out exactly what's going on while having to change files (mental contexts) so frequently. This is especially difficult if just browsing the code on Github or a text editor without convenient go-to-declaration or go-to-usages functionality.

Additionally, the fact that these demos are located in the abjad package itself (which may be improper packaging etiquette in the first place) means that many users will be reading through the demos without going along with the walkthroughs in the docs. The lack of proper docstring annotations in the demos makes this sort of reading especially confusing.

Ideally I think the demos would be formatted in self-contained scripts whose in-file documentation follows [literate programming](https://en.wikipedia.org/wiki/Literate_programming) principles, and they would probably not be placed in the abjad `pip install`-able package at all.

**Comment by josiah-wolf-oberholtzer** [comment]
@ajyoon I'm amenable to putting all functions/classes for a given demo into the same module. That does make some pedagogical sense and I'm sympathetic to the mental overhead of context switching. Navigating multiple inter-related files is certainly something that people grappling with programming need to overcome through practice, and it's hard, and I don't *have* to set it up like that for the demos 😆. 

Additionally, those demo functions do deserve some docstrings, although perhaps not a full literate programming make-over.

I'm not amenable to removing the demos from the pip-installable package because our documentation system actually pulls them in for code-excerpting via module path references. See the `..  import:: ...` statements in https://raw.githubusercontent.com/Abjad/abjad/master/abjad/docs/source/literature_examples/ferneyhough.rst for example. These are actually locating the code in the examples and pulling them in a Python interpreter session during the doc-building process, allowing us to "play" with the demo functions in the documentation itself. If the demos aren't importable, we can't do that, and the demo code shown in the docs will drift from the real demo code (as it has historically before we implemented this excepting system).

**Comment by trevorbaca** [comment]
Still valid in June 2017.

**Comment by trevorbaca** [comment]
Ferneyhough demo is now refactored as a class. Provides pattern to refactor other demos when we decide to do so.

Closing issue.
