### ISSUE TITLE
Appending items from a duplicated sequence to Staff()

### ISSUE THREAD

**Issue by amirteymuri** [Abjad/abjad#772]
Why is iterating over a duplicated list / tuple of components and appending them to a Staff() not working? Here is the code:

from abjad import *
score =Score()
time_signature = indicatortools.TimeSignature((6, 4))
tempo = Tempo(Duration(1, 4), 60)
#flute
flute = instrumenttools.Flute()
fl_staff = Staff(context_name = "RhythmicStaff")
first_quarter = Note("c4")
tuplet = Tuplet(Multiplier(4, 5), "c16[ c4]")
tuplet1 = Tuplet(Multiplier(4, 5), "c8[ c8.]")
tuplet2 = Tuplet(Multiplier(4, 5), "c8.[ c8]")
tuplet3 = Tuplet(Multiplier(4, 5), "c4[ c16]")
last_quarter = Note("c4")
tuplets = (first_quarter, tuplet, tuplet1, tuplet2, tuplet3, last_quarter)

#duplicate the tuple
    tuplets *= 2

#iterate over the duplicated, but the score will contain only the original tuple, why?
    for t in tuplets:
        print t
        fl_staff.append(t)
score.append(fl_staff)
attach(tempo, fl_staff)
attach(flute, fl_staff)
attach(time_signature, fl_staff)
show(score)

**Comment by josiah-wolf-oberholtzer** [comment]
A "score component" can only have one parent, and can only exist in one position in that parent.

You are attempting to add identical score components multiple times to the same parent.

Rather than duplicate the list - which doesn't duplicate the components, but only duplicates _references_ to those components - you should make sure that the score components you are appending into the score are always unique.

Study the following code example:

```
from abjad import *

score = Score()
time_signature = indicatortools.TimeSignature((6, 4))
tempo = Tempo(Duration(1, 4), 60)

flute = instrumenttools.Flute()
flute_staff = Staff(context_name = "RhythmicStaff")

for _ in range(2):
    first_quarter = Note("c4")
    tuplet = Tuplet(Multiplier(4, 5), "c16[ c4]")
    tuplet1 = Tuplet(Multiplier(4, 5), "c8[ c8.]")
    tuplet2 = Tuplet(Multiplier(4, 5), "c8.[ c8]")
    tuplet3 = Tuplet(Multiplier(4, 5), "c4[ c16]")
    last_quarter = Note("c4")
    components = (first_quarter, tuplet, tuplet1, tuplet2, tuplet3, last_quarter)
    flute_staff.extend(components)

score.append(flute_staff)
attach(tempo, flute_staff)
attach(flute, flute_staff)
attach(time_signature, flute_staff)
show(score)
```

Rather than duplicate the list via `tuplets *= 2`, I make sure to create _new_ score components by creating those components inside a loop.
