### ISSUE TITLE
concatenate or merge different containers

### ISSUE THREAD

**Issue by uummoo** [Abjad/abjad#876]
Hey everyone,

first of all thank you for your great work! 
 
How is it possible to merge or concatenate different `Container`-objects to a new object? The only way, that worked for me, was kind of ugly:

```python
import abjad
n0 = abjad.Note(0, abjad.Duration(3,8)) 
n1 = abjad.Note(1, abjad.Duration(2,8))
n2 = abjad.Note(2, abjad.Duration(4,8))
a = abjad.Container([n0, n1])
b = abjad.Container([n2])
c = abjad.Container()
for el in a[:]:
    c.append(el)
for el in b[:]:
    c.append(el)
print(c)
```

> Container("c'2 c'2 ef'2")

But then `a` and `b` are getting empty:

```python
print(a)
```
> Container()

```python
print(b)
```
> Container()

Is there any special reason why you didn't implemented a concatenation via the plus operator?

```python
c = a + b
```

> TypeError: unsupported operand type(s) for +: 'Container' and 'Container'

Or if I try to initialize a new `Container` with two merged `Selection`-objects:
```python
c = Container(a[:] + b[:])
```
> TypeError: can not initialize container from Selection([Note("c'4."), Note("cs'4"), Note("d'2")]). try using mutate().wrap()?

I don't understand this Error-Message. If I try to make a new independent `Container` with `mutate`:

```python
a_mut = abjad.mutate(a)
b_mut = abjad.mutate(b)
c = abjad.Container()
a_mut.wrap(c)
b_mut.wrap(c)
```

> Exception: must be empty container: <{1}>.

The only way to merge two `Container`-objects without affecting the original objects I could still imagine would be to make `mutate`-objects, copying them, creating a new empty `Container` and finally adding every element of the copied `Container`-objects to the empty new object, which is super complicated for such an easy operation. Another problem is, that I might loose information, which I might have already attached to one of the `Conatiner`-objects (like Tie()). Is there really no better way? Or is abjad just not meant to work within a more functional approach?

Best regards

**Comment by josiah-wolf-oberholtzer** [comment]
Abjad score components (notes, rests, containers, measures, staves, etc.) may have only one parent. Appending or extending a component into another container removes the reference to the original parent and replaces it with the new parent, resulting in the removal behavior you see here. It does not duplicate or otherwise copy the component during the append/extend/set-item process.

If you want to maintain the contents of your original containers while creating a new container whose contents appears to be a merged version of those containers, use `mutate(...).copy()` on the original containers and merge the contents of the resulting copies.
