### ISSUE TITLE
Minor mistake in the definition of assignability in the documentation.

### ISSUE THREAD

**Issue by kureta** [Abjad/abjad#897]
> **assignability**:  a duration ``n/d`` is assignable when and only when numerator ``n`` is of the form ``k(2**u-j)`` and denominator ``d`` is of the form ``2**v``.  In this definition ``u`` and ``v`` must be nonnegative integers, ``k`` must be a positive integer, and ``j`` must be either ``0`` or ``1``.

If `u = 0` and `j=1` then `n=0`, which satisfies the defined constraints but results in `0` duration, which is not assignable.

**Comment by trevorbaca** [comment]
@kureta Agreed. And, actually, I'm not sure how ``k`` got put into that definition either. Because ``5(2**1-1)/2**1`` gives ``5/2``, which definitely violates assignability in the numerator.

Changed to this:

<img width="728" alt="assignability" src="https://user-images.githubusercontent.com/5804733/62900361-f4350380-bd27-11e9-8299-dc31c0855a19.png">

Can you verify?
